### ISSUE TITLE
ImportError: cannot import name 'accuracy_jaccord'

### ISSUE THREAD

**Issue by swidi** [fabrahman/Emo-Aware-Storytelling#3]
I installed fast_bert as described but there is one particular import that is not working:
```
>>> from fast_bert.metrics import accuracy_jaccord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'accuracy_jaccord'
```
This leads to `run_bert_classifier.py` failing.

Do you know if a very specific version of fast_bert or sklearn are required? No version is specified in fast_berts' requirements.txt

**Comment by shaoniana1997** [comment]
Dear Sir,can i have you personal email ! Because i am trying to reproduce this code but i am a rookie!
I am sorry to bother you~sincerely! @swidi

**Comment by xinli2008** [comment]
Yes,I found the same error! i doubt if the author of fast_bert update the code ?
And have you solved the question ?  Yours sincerely! @swidi

**Comment by fabrahman** [comment]
@swidi @shaoniana1997  Please add the following function in the [metrics.py ](https://github.com/utterworks/fast-bert/blob/308aa9e7700e923a428a9a937ff8d89a3397c865/fast_bert/metrics.py#L52):

```
def accuracy_jaccord(y_pred: Tensor, y_true: Tensor, thresh: float = CLASSIFICATION_THRESHOLD, sigmoid: bool = True):
    if sigmoid:
        y_pred = y_pred.sigmoid()
    return jaccard_score(y_pred > thresh, y_true.bool(), average='samples')
```

I am closing this issue for now. Feel free to reopen.

**Comment by xinli2008** [comment]
thank you for your timely reply!

**Comment by xinli2008** [comment]
when i use the accuracy_jaccord to evaluate ,if always reminds the information :
TypeError: accuracy_jaccord() got an unexpected keyword argument 'labels'
can you give me some useful advice? @fabrahman
