### ISSUE TITLE
Question about the run_emorl.sh

### ISSUE THREAD

**Issue by xinli2008** [fabrahman/Emo-Aware-Storytelling#4]
Hello, your job is excellent ,i am trying to reproduce your project .
when i do :bash run_emotl.sh ，It prompts for an error message：
Traceback (most recent call last):
  File "train_rl.py", line 36, in <module>
    from Reinforcement.rewards_v2 import get_reward, format_generated_stories_for_clf, _get_text, generate_all_valid_sample_dict
  File "/home/lixin/Emo-Aware-Storytelling-master/Reinforcement/rewards_v2.py", line 39, in <module>
    with open(os.path.join(SCORE_PATH, 'word2index.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'comet-commonsense/precomputed_similarities/word2index.pkl'

and in you code ,you write : 
SCORE_PATH = 'comet-commonsense/precomputed_similarities/'
with open(os.path.join(SCORE_PATH, 'word2index.pkl'), 'rb') as f:
    word2ind = pickle.load(f)

Because i found no useful information in comet , so i wonder if you miss some necessary data?
can you give me some useful advide ? Thank you very much ! @fabrahman

**Comment by fabrahman** [comment]
Please find the requested files [here](https://drive.google.com/file/d/1AH8eGG6ORiBjcljMH5Vc8UN8mDQBqaWi/view?usp=sharing).
I will update the readme.

**Comment by xinli2008** [comment]
Thank you very much! wish you have a nice day! ^^^
